export const commonTopics = [
  "JavaScript",
  "Python",
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "HTML",
  "CSS",
  "Git",
  "GitHub",
  "MongoDB",
  "SQL",
  "PostgreSQL",
  "API Development",
  "REST APIs",
  "GraphQL",
  "Data Structures",
  "Algorithms",
  "Machine Learning",
  "Artificial Intelligence",
  "Deep Learning",
  "Computer Science",
  "Web Development",
  "Mobile Development",
  "iOS Development",
  "Android Development",
  "Cloud Computing",
  "AWS",
  "Azure",
  "Google Cloud",
  "DevOps",
  "Docker",
  "Kubernetes",
  "Cybersecurity",
  "Blockchain",
  "Cryptocurrency",
  "UI/UX Design",
  "Product Management",
  "Agile Methodology",
  "Scrum",
  "Project Management",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Literature",
  "Philosophy",
  "Psychology",
  "Economics",
  "Business",
  "Marketing",
  "Finance",
  "Accounting",
  "Art History",
  "Music Theory",
  "Film Studies",
  "Sports",
  "Nutrition",
  "Health & Fitness",
  "Cooking",
  "Travel",
  "Photography",
  "Gardening",
];

export const filterTopics = (input: string, topics: string[]): string[] => {
  if (!input) return topics.slice(0, 10); // Show top 10 when empty

  const lowerInput = input.toLowerCase();
  return topics
    .filter((topic) => topic.toLowerCase().includes(lowerInput))
    .slice(0, 10); // Limit to 10 results
};
